setup.py: Oops, the module name is 'spam' not 'spammify'
With the old version you get:

  ImportError: dynamic module does not define init function (PyInit_spammify)